epochs:
  desc: number of epochs
  value: 100

num_layers:
  desc: number of layers of the network
  value: 3

channels:
  desc: channels of cnn layers
  value: 5

kernel_size:
  desc: size of cnn filter kernel
  value: 3

learning_rate:
  desc: learning rate
  value: 0.001

input_dimensions:
  desc: input dimensions
  value:
    height: 28
    width: 28

model_folder:
  desc: where models are saved
  value: 'models'