# Dataset

dataset_name:
  desc: name of the dataset to use ['mnist', 'cifar10']
  value: 'cifar10'

train_dataset_size:
  desc: number of samples in the train set
  value: 500

val_dataset_size:
  desc: number of samples in the validation set
  value: 50

# Train loop parameters

epochs:
  desc: number of epochs
  value: 100

batch_size:
  desc: batch size
  value: 32

# Optimizer

learning_rate:
  desc: learning rate
  value: 0.001

weight_decay:
  desc: L2 regularization
  value: 0.00001

# Model selection

model_type:
  desc: which model to use ['cnn']
  value: 'cnn'

# CNN

num_layers:
  desc: number of layers of the network
  value: 3

channels:
  desc: channels of cnn layers
  value: 5

kernel_size:
  desc: size of cnn filter kernel
  value: 3

# Saving the model

model_folder:
  desc: where models are saved
  value: 'models'